on:
  push:
    paths:
      - "**"

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn test
      - if: github.ref == 'refs/heads/main'
        run: echo "deploying 1.0.${GITHUB_RUN_NUMBER}"
